# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "energiemeldungen", # <sankeyEnergiemeldungen>
  "Altes Heizsystem", # <sankeyEnergiemeldungen>
  "Neues Heizsystem", # <sankeyEnergiemeldungen>
  "alt", # <sankeyEnergiemeldungen>
  "neu", # <sankeyEnergiemeldungen>
  NULL
))
